# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mode_of_login',
            field=models.CharField(default='SSO', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='programme_of_study',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
