# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171127_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme_of_study',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Post-Doctorate', 'Post-Doctorate')], max_length=20, null=True),
        ),
    ]
