# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_student_avaiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
