# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171201_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='college_name',
            new_name='college',
        ),
    ]
