# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20171202_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='avaiable',
            new_name='available',
        ),
    ]
